### ISSUE TITLE
Refused to execute script from 'https://jsfiddle.net/api/

### ISSUE THREAD

**Issue by cyberjetx** [jsfiddle/jsfiddle-issues#1288]
The following simplified previously working code:

```  
$.ajax({
    type: 'GET',
    dataType: 'json',
    data: {},
    url: "http://jsfiddle.net/api/user/afabbro/demo/list.json",
    error: function (jqXHR, textStatus, errorThrown) {
        console.log(jqXHR)
    },
    success: function (msg) {
        console.log(msg);
    }
  });
```

I receive the following error:

```Refused to execute script from 'http://jsfiddle.net/api/user/afabbro/demo/list.json?
callback=jQuery332 ...SNIPd... &_=1553587384' because its MIME type ('application/json') 
is not executable, and strict MIME type checking is enabled.
```

I initially thought that the issue was http vs https. All attempts return the same result.

if you run from the addy bar the browser identifies the mime correctly & you get the json as expected:

```[
{
"framework": "No-Library",
"version": 8,
"description": "",
"title": "Hello World Example",
"url": "//jsfiddle.net/afabbro/vrVAP/",
"author": "afabbro",
"latest_version": 12520,
"created": "2013-08-08 15:03:20"
}
]
```

The code worked as recently as yesterday. Is there a _preferred_ method I should use?

**Comment by oskarkrawczyk** [comment]
Switched backend yesterday, still has a few bugs. Looking into it.

**Comment by oskarkrawczyk** [comment]
Fixed

**Comment by cyberjetx** [comment]
Can you take a quick look at this fiddle and tell me what I am screwing up? Still getting the Cross-Origin Read Blocking (CORB) error even on jsfiddle.net? 

https://jsfiddle.net/Cyberjetx/6m5us540/32/
