### ISSUE TITLE
GitHub integration not supporting non-master branches

### ISSUE THREAD

**Issue by stephencookdev** [jsfiddle/jsfiddle-issues#1420]
Any non-master branches won't work with GitHub integration

e.g.:

 * https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/compare/ works as expected
 * https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/v7.0.2/samples/stock/demo/compare/

If you look at the error that JSFiddle is throwing, it's saying

```
Repository/Gist not found: https://api.github.com/repos/highcharts/highcharts/contents/v7.0.2/samples/stock/demo/compare
```

which is true, because JSFiddle has tried to include the branch name in the file path. The URL that JSFiddle should have instead generated to pass to GitHub's API is:

```
https://api.github.com/repos/highcharts/highcharts/contents/samples/stock/demo/compare?ref=v7.0.2
```

This was previously raised in https://github.com/jsfiddle/jsfiddle-issues/issues/1280 - but was closed as stale. Optimistically re-raising, as it really would be great to have this working!

As a guess, all that's happening here is that the URL grepping logic is looking for `tree/master/`, `tree/` or `/` and then takes everything following that as the path. The fix here should be fairly simple, it should just be `tree/([^/]+/)`, or `/`, everything following as the path, and then `?ref=` either the regex matching group, or `master` as a fallback

**Comment by oskarkrawczyk** [comment]
Since we have a new backend I'm optimistic this can be altered to include non-master branches.

**Comment by oskarkrawczyk** [comment]
Should be working 🤙🏻

**Comment by stephencookdev** [comment]
@oskarkrawczyk thanks for the quick response :smile: 

Unfortunately I don't think this is working yet :disappointed: Now JSFiddle _accepts_ URLs with non-master branches, but it still doesn't add in the `?ref=branch_name`

e.g. https://jsfiddle.net/gh/get/library/pure/onfido/onfido-sdk-ui/tree/fiddletest/demo/fiddle doesn't work, throwing an error stating:

```
Repository/Gist not found: https://api.github.com/repos/onfido/onfido-sdk-ui/contents/demo/fiddle
```

since https://api.github.com/repos/onfido/onfido-sdk-ui/contents/demo/fiddle returns a 404

But it should be https://api.github.com/repos/onfido/onfido-sdk-ui/contents/demo/fiddle?ref=fiddletest which does not 404

**Comment by oskarkrawczyk** [comment]
Hmm, I'll look into it tomorrow, no promises though

**Comment by stefaniacardenas** [comment]
Hi, any update on this?

**Comment by greenred123** [comment]
Would also love to be able to use this with non-master branches!

**Comment by jamesmurdza** [comment]
I just created a new GitHub repo to test with JSFiddle. Of course, GitHub is using **main** as the default branch for new projects days.

And when going to https://jsfiddle.net/gh/get/library/pure/jamesmurdza/repo/tree/main/demo I received "404 Repository/Gist not found".

I then renamed my GitHub **main** branch to **master**. The same link (above) suddenly worked. Finally, I renamed the branch back to **main** and everything continued to work.

This is probably only working for me due to the fact that GitHub is now redirecting **master** to **main**. So it seems, without a **master** branch, JSFiddle ignores GitHub repos.
