### ISSUE TITLE
Find in page only searches visible parts of code

### ISSUE THREAD

**Issue by ultrapasty** [jsfiddle/jsfiddle-issues#749]
The browser's built-in "Find in page" utility only searches parts of the code that are currently visible.

To reproduce:

1. Visit https://jsfiddle.net/1Lqb1vb1/
2. Use browser's "Find in page" utility to search for the phrase "Find me" 
3. There are 8 instances of "Find me" on the fiddle, one at the top and bottom of each pane. The browser finds the instances at the top of each code pane, and the top and bottom of the result window, but not at the bottom of each code pane.

Reproducible in:

- Chrome 49.0.2623.112 / Mac OS X
- Safari 9.1 / Mac OS X
- Firefox 43.0.4 / Mac OS X
- Possibly windows as well but unable to test that.

Thanks for your work on JSFiddle :heart:

**Comment by ultrapasty** [comment]
Looks like it's a problem with CodeMirror - see [issue 50](https://github.com/NUKnightLab/learncms/issues/50). They have a solution here: https://codemirror.net/demo/search.html - do you reckon it would be worth implementing this?

**Comment by DozenalFTW** [comment]
We should just implement our own find so we can have Find and Replace as well.

**Comment by oskarkrawczyk** [comment]
Updated CodeMirror, should fix the issue.

**Comment by ultrapasty** [comment]
Thanks for the update. It doesn't seem to have changed the behaviour outlined above, but it's not a big deal.

**Comment by donhatch** [comment]
Yes, thanks for the update :-)  But since it didn't fix the problem, please reopen the issue!
