### ISSUE TITLE
Dojo is inaccesible over https

### ISSUE THREAD

**Issue by barbsan** [jsfiddle/jsfiddle-issues#984]
After changing dojo paths in #959 to http://archive.dojotoolkit.org/cdn/{version}-cdn/... they can't be loaded over https (as jsfiddle is).
Now to use dojo in new fiddles one has to fork old fiddles or add  as <script>.

Dojo Toolkit's website suggests to use sources from Google CDN, some recent versions I've found:
https://ajax.googleapis.com/ajax/libs/dojo/1.10.7/dojo/dojo.js
https://ajax.googleapis.com/ajax/libs/dojo/1.11.3/dojo/dojo.js
https://ajax.googleapis.com/ajax/libs/dojo/1.12.1/dojo/dojo.js

**Comment by oskarkrawczyk** [comment]
@barbsan Thanks for reporting this in. I've contacted @dylans from Dojo to see if it's possible to turn SSL on, on their CDN.

In the mean time, just switch JSFiddle to HTTP (in the location bar) for the resources to work.

**Comment by barbsan** [comment]
@oskarkrawczyk Thanks for advice, but I've already attached dojo resources from Google CDN using <script>. I just hope fixing this would help others.

BTW this wouldn't work for fiddles with unsaved draft, because they are forced to be loaded over https (browsers keep autocompleting "s" in location bar). Sometimes I have to check something without need of saving it.

**Comment by dylans** [comment]
This should be resolved now, thanks for bringing it to our attention.

**Comment by barbsan** [comment]
Thank you, but it seems that problem remains for version 1.10.8

**Comment by oskarkrawczyk** [comment]
Fixed
